---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: mickblue
# description will be included in the image's metadata
description: Mick's personal Bluefin image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /


  - type: rpm-ostree
    install:
       - open-vm-tools
       - open-vm-tools-desktop
       - virtualbox-guest-additions
       # yubikey enablement
       - pam-u2f
       - pam_yubico
       - pamu2fcfg
       - yubikey-manager


  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - io.mpv.Mpv
        - org.qbittorrent.qBittorrent
        - me.kozec.syncthingtk
    
        #Bluefin
        - app/io.github.dvlv.boxbuddyrs/x86_64/stable
        - app/com.github.rafostar.Clapper/x86_64/stable
        - app/org.fedoraproject.MediaWriter/x86_64/stable
        - app/com.github.tchx84.Flatseal/x86_64/stable
        - app/io.github.flattool.Warehouse/x86_64/stable
        - app/org.gnome.baobab/x86_64/stable
        - app/org.gnome.Calculator/x86_64/stable
        - app/org.gnome.Calendar/x86_64/stable
        - app/org.gnome.Characters/x86_64/stable
        - app/org.gnome.clocks/x86_64/stable
        - app/org.gnome.Connections/x86_64/stable
        - app/org.gnome.Contacts/x86_64/stable
        - app/org.gnome.DejaDup/x86_64/stable
        - app/org.gnome.Papers/x86_64/stable
        - app/com.mattjakeman.ExtensionManager/x86_64/stable
        - app/org.gnome.FileRoller/x86_64/stable
        - app/org.gnome.font-viewer/x86_64/stable
        - app/org.gnome.Logs/x86_64/stable
        - app/org.gnome.Loupe/x86_64/stable
        - app/org.gnome.Maps/x86_64/stable
        - app/org.gnome.NautilusPreviewer/x86_64/stable
        - app/org.gnome.World.PikaBackup/x86_64/stable
        - app/org.gnome.TextEditor/x86_64/stable
        - app/org.gnome.Weather/x86_64/stable
        - app/io.missioncenter.MissionCenter/x86_64/stable
        - app/org.mozilla.firefox/x86_64/stable
        - runtime/org.gtk.Gtk3theme.adw-gtk3/x86_64/3.22
        - runtime/org.gtk.Gtk3theme.adw-gtk3-dark/x86_64/3.22
    user: {} # Also add Flathub user repo, but no user packages


  - type: gnome-extensions
    install:
        - Add to Desktop
        - Wiggle
        - WTMB (Window Thumbnails) 
        - Caffeine
      
    uninstall:
        -  AppIndicator and KStatusNotifierItem Support
        -  Apps Menu
        -  Blur my Shell
        -  Dash to Dock
        -  Logo Menu
        

  - type: chezmoi
    repository: "https://github.com/Mick100864/dotfiles_public" # my dotfiles repo
    all-users: false # make users have to enable chezmoi manually
    file-conflict-policy: replace # override changed files with those from the repo
    
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
